### ISSUE TITLE
Update to work with Kube 1.22?

### ISSUE THREAD

**Issue by ksdeepak93** [banzaicloud/kube-metrics-adapter#24]
## Expected Behavior
Mertics-adapter is installed on cluster

## Actual Behavior
Chart is not installed as "the server could not find the requested resource"
kind "apiregistration.k8s.io/v1beta1/APIService" for "external-metrics-apiservice" (v1beta1.external.metrics.k8s.io)

## Steps to Reproduce the Problem

````yaml
apiVersion: v2
version: "1.0.0"
name: kube-metrics-adapter
dependencies:
  - name: kube-metrics-adapter
    version: "0.1.3"
    repository: "https://kubernetes-charts.banzaicloud.com"
````
Install chart 

## Specifications

- The apiregistration.k8s.io/v1beta1 API version of APIService is no longer served as of v1.22.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

## solution 
- Bump the API version. (API clients to use the apiregistration.k8s.io/v1 API version)

  - kube Version: 1.22
  - Platform: linux/amd64
  - Subsystem:
